# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesuperfan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nowplayingmovie',
            name='add_movie_collection',
        ),
    ]
