# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesuperfan', '0002_remove_nowplayingmovie_add_movie_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermovie',
            old_name='movie_rating',
            new_name='movie_review',
        ),
    ]
