# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesuperfan', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joined_date',
            field=models.DateTimeField(),
        ),
    ]
