# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesuperfan', '0005_auto_20170429_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
