# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesuperfan', '0006_auto_20170429_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NowPlayingMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200, unique=True)),
                ('movie_overview', models.CharField(max_length=1000)),
                ('movie_poster_url', models.CharField(max_length=200)),
                ('movie_release_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='movie_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesuperfan.NowPlayingMovie'),
        ),
    ]
