# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesuperfan', '0007_auto_20170501_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowplayingmovie',
            name='movie_poster_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='nowplayingmovie',
            name='movie_title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
